- name: "Install kibana"
  yum:
    name: "{{ kibana_repo_redhat }}"
    state: latest

- name: "Enable kibana"
  systemd:
    name: kibana
    enabled: yes

- name: "Start kibana"
  systemd:
    name: kibana
    state: started
    