- name: "Update the system"
  yum:
    name: '*'
    state: latest
  become: yes

- name : "Install prerequisite"
  yum:
    name: [java-1.8.0-openjdk, java-1.8.0-openjdk-devel]
    state: latest
  become: yes

- name: "Install kibana"
  yum:
    name: "{{ kibana_repo_redhat }}"
    state: latest
  become: yes

- name: "Copy config file"
  copy:
    src: "../files/kibana.yml"
    dest: "/etc/kibana/kibana.yml"
  become: yes

- name: "Enable kibana"
  systemd:
    name: kibana
    enabled: yes
  become: yes

- name: "Start kibana"
  systemd:
    name: kibana
    state: started
  become: yes
    