- name: "Update the system"
  yum:
    name: '*'
    state: latest
  become: yes

- name : "Install prerequisite"
  yum:
    name: {{item}}
    state: latest
  become: yes
  with_items:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel

- name: "Install kibana"
  yum:
    name: "{{ kibana_repo_redhat }}"
    state: latest
  become: yes

- name: "Copy config file"
  copy:
    src: "../files/kibana.yaml"
    dest: "/etc/kibana/kibana.yaml"
  become: yes

- name: "Enable kibana"
  systemd:
    name: kibana
    enabled: yes
  become: yes

- name: "Start kibana"
  systemd:
    name: kibana
    state: started
  become: yes
    