---
- name: "Install Kibana in RedHat systems"
  include: kibana-{{ redhat_system }}.yml
  when: ansible_os_family == "RedHat"

- name: "Install Kibana in Debian Systems"
  include: kibana-{{ debian_system }}.yml
  when: ansible_os_family == "Debian"
